### ISSUE TITLE
Bug in the Jacobian computation caused by  variable not being initialized 

### ISSUE THREAD

**Issue by josimarsilva** [josimarsilva/pylith#6]
There seems to be memory leak or error in the Jacobian computations that is causing the unit tests for poroelasticity to fail. It seems that some variable (s) are not being initialized.

**Comment by baagaard-usgs** [comment]
This is likely due to errors in indexing into the `s`, `sOff`,  `a`, or `aOff` arrays. `sOff` contains the offset of each subfield into the `s` array. The index into the sOff` array is the subfield index. So the first component of the solution for the second subfield is stored at `s[sOff[1]]`. Normally, we first set the index of the subfield and then get the first component of the subfield:

```
const PyLith int i_disp = 0; // displacement is the first subfield
const PyLithScalar* disp = s[sOff[i_disp]];
```

Some things to check: 
1. Make sure the subfield indices are correct. They should match the `s` and `a` being passed in, not the original `s` or `a` that might be larger.
2. Make sure the call to the function passes matching info for `s`, `sOff` and `sOff_x` (ditto for the auxiliary field). That is, if a subset of subfields are being passed, then you need to create a subset for all three.
3. Use the debugger to check the values for all of the arguments coming in to make sure they make sense. First check the offsets, then check the solution and auxiliary field values.

**Comment by josimarsilva** [comment]
I went through the Jacobians and residuals files again. I still haven't found an issue with the indexes of `s, soff,a` or `aoff`. I will follow up with a presentation with some other details.

I am having trouble getting valgrind installed,  if I manage to install it I will look into point #3.

**Comment by josimarsilva** [comment]
Solved
